modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
credits="Inspired by Journeymap Integrations (for FTB claims)"
authors="${mod_author}"
displayTest="IGNORE_ALL_VERSION"
logoFile="logo.png"
description='''
Journeymap integration for Open Parties and Claims (by Xaero).
'''

[[dependencies.journeypac]]
	modId="forge"
	mandatory=true
	versionRange="[47.1,)"
	ordering="NONE"
	side="CLIENT"

[[dependencies.journeypac]]
	modId="journeymap"
	mandatory=true
	versionRange="[5.9.8,)"
	ordering="NONE"
	side="CLIENT"

[[dependencies.journeypac]]
	modId="openpartiesandclaims"
	mandatory=true
	versionRange="[0.17.5,)"
	ordering="NONE"
	side="CLIENT"
