plugins {
	id "net.fabricmc.fabric-loom" version "1.15-SNAPSHOT"
}

base {
	archivesName = "${mod_name}-fabric-${minecraft_version}"
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

	implementation "maven.modrinth:open-parties-and-claims:fabric-26.1.2-0.26.3"
	compileOnly("info.journeymap:journeymap-api-fabric:2.0.0-26.1-SNAPSHOT") {changing = true}
	runtimeOnly "maven.modrinth:journeymap:26.1-6.0.0-beta.67+fabric"
}

loom {
	mods {
		"${mod_id}" {
			sourceSet sourceSets.main
		}
	}

	runs {
		client {
			client()
			setConfigName("Fabric Client")
			ideConfigGenerated(true)
			runDir("run")
		}

		remove server
	}
}
tasks.runServer.enabled = false

processResources {
	from project(":common").sourceSets.main.resources
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "mod_id": project.mod_id, "version": project.version,
			"mod_name": project.mod_name, "mod_author": project.mod_author
	}
}

tasks.withType(JavaCompile) {
	source(project(":common").sourceSets.main.allSource)
}
