plugins {
	id "fabric-loom" version "1.11-SNAPSHOT"
}

base {
	archivesName = "${mod_name}-fabric-${minecraft_version}"
}

configurations {
	modRuntimeOnly.extendsFrom modRuntimeNest
}

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
	implementation project(":common")

	modRuntimeNest "maven.modrinth:forge-config-api-port:xSFUjnSg" // 21.9.7
	modImplementation "maven.modrinth:open-parties-and-claims:fabric-1.21.9-0.25.6"
	modApi("info.journeymap:journeymap-api-fabric:2.0.0-1.21.9-SNAPSHOT") {changing = true}
	modRuntimeNest "maven.modrinth:journeymap:1.21.9-6.0.0-beta.53+fabric"

	// loom strips nested jars, this adds them back in
	modRuntimeOnly configurations.modRuntimeNest.incoming.files.collect {
		zipTree(it).matching {
			include "META-INF/jars/*.jar"
		}
	}
}

loom {
	runs {
		client {
			client()
			setConfigName("Fabric Client")
			ideConfigGenerated(true)
			runDir("run")
		}

		remove server
	}
}
tasks.runServer.enabled = false

processResources {
	from project(":common").sourceSets.main.resources
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "mod_id": project.mod_id, "version": project.version,
			"mod_name": project.mod_name, "mod_author": project.mod_author
	}
}

tasks.withType(JavaCompile) {
	source(project(":common").sourceSets.main.allSource)
}
