pluginManagement {
	repositories {
		gradlePluginPortal()

		mavenCentral()

		maven {
			name = "Sponge Snapshots"
			url = "https://repo.spongepowered.org/repository/maven-public/"
		}
	}
}

rootProject.name = "JourneyPAC"
// Forge doesn't support gradle 9 yet
include("common", /*"forge",*/ "neoforge", "fabric")
