plugins {
	id "net.minecraftforge.gradle" version "[6.0.36,6.2)"
}

archivesBaseName = "${mod_name}-forge-${minecraft_version}"

minecraft {
	mappings channel: "official", version: minecraft_version
	reobf = false

	if (project.hasProperty("forge_ats_enabled") && project.findProperty("forge_ats_enabled").toBoolean()) {
		// This location is hardcoded in Forge and can not be changed.
		// https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
		accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")
		project.logger.debug("Forge Access Transformers are enabled for this project.")
	}

	runs {
		client {
			workingDirectory project.file("run")
			property "forge.logging.markers", "REGISTRIES"
			property "forge.logging.console.level", "debug"
			property "eventbus.api.strictRuntimeChecks", "true"

			mods {
				journeypac {
					source sourceSets.main
				}
			}
		}
	}
}

repositories {
	maven {
		name = "Forge"
		url = "https://maven.minecraftforge.net"
	}

	maven {
		name = "Minecraft libraries"
		url = "https://libraries.minecraft.net"
	}
}

dependencies {
	minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
	annotationProcessor "net.minecraftforge:eventbus-validator:7.0-beta.10"
	compileOnly project(":common")

	runtimeOnly "maven.modrinth:forge-config-api-port:v21.8.0-1.21.8-Forge"
	implementation "maven.modrinth:open-parties-and-claims:forge-1.21.8-0.25.8"
	compileOnly("info.journeymap:journeymap-api-forge:2.0.0-1.21.7-SNAPSHOT") {changing = true}
	runtimeOnly "maven.modrinth:journeymap:1.21.8-6.0.0-beta.52+forge"
}

tasks.withType(JavaCompile) {
	source(project(":common").sourceSets.main.allSource)
}

processResources {
	from project(":common").sourceSets.main.resources

	filesMatching("META-INF/mods.toml") {
		expand "mod_id": project.mod_id, "version": project.version,
			"mod_name": project.mod_name, "mod_author": project.mod_author
	}
}

sourceSets.each {
	def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
	it.output.resourcesDir = dir
	it.java.destinationDirectory = dir
}
