plugins {
	id "net.minecraftforge.gradle" version "[7.0.3,8)"
}

base {
	archivesName = "${mod_name}-forge-${minecraft_version}"
}

minecraft {
	mappings channel: "official", version: minecraft_version

	if (project.hasProperty("forge_ats_enabled") && project.findProperty("forge_ats_enabled").toBoolean()) {
		// This location is hardcoded in Forge and can not be changed.
		// https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
		accessTransformer = file("src/main/resources/META-INF/accesstransformer.cfg")
		project.logger.debug("Forge Access Transformers are enabled for this project.")
	}

	runs {
		client {
			workingDir = project.file("run")
			systemProperty "forge.logging.markers", "REGISTRIES"
			systemProperty "forge.logging.console.level", "debug"
			systemProperty "eventbus.api.strictRuntimeChecks", "true"

			mods {
				"${mod_id}" {
					source sourceSets.main
				}
			}
		}
	}
}

repositories {
	minecraft.mavenizer(it)
	maven fg.forgeMaven
	maven fg.minecraftLibsMaven
}

dependencies {
	implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
	annotationProcessor "net.minecraftforge:eventbus-validator:7.0-beta.12"
	compileOnly project(":common")

	runtimeOnly "maven.modrinth:forge-config-api-port:26.1.4"
	compileOnly "maven.modrinth:open-parties-and-claims:forge-1.21.11-0.25.10" // not updated yet, use as API only
	compileOnly("info.journeymap:journeymap-api-forge:2.0.0-26.1-SNAPSHOT") {changing = true}
	runtimeOnly "maven.modrinth:journeymap:26.1-6.0.0-beta.67+forge"
}

tasks.withType(JavaCompile) {
	source(project(":common").sourceSets.main.allSource)
}

processResources {
	from project(":common").sourceSets.main.resources

	filesMatching("META-INF/mods.toml") {
		expand "mod_id": project.mod_id, "version": project.version,
			"mod_name": project.mod_name, "mod_author": project.mod_author
	}
}

sourceSets.each {
	def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
	it.output.resourcesDir = dir
	it.java.destinationDirectory = dir
}
