plugins {
	id "org.spongepowered.gradle.vanilla" version "0.3.2"
}

base {
	archivesName = "${mod_name}-common-${minecraft_version}"
}

minecraft {
	version(minecraft_version)
}

dependencies {
	// neoforge dependency (with unobfuscated class names) because OPaC doesn't publish dev jars
	compileOnly "maven.modrinth:open-parties-and-claims:neoforge-26.1.2-0.26.3"
	compileOnly("info.journeymap:journeymap-api-common:2.0.0-26.1-SNAPSHOT") {changing = true}
}

processResources {
	def buildProps = project.properties.clone()

	filesMatching(["pack.mcmeta"]) {
		expand buildProps
	}
}
