plugins {
	id "net.neoforged.moddev" version "2.0.115"
}

base {
	archivesName = "${mod_name}-neoforge-${minecraft_version}"
}

configurations {
	runtimeClasspath.extendsFrom localRuntime
}

neoForge {
	version = project.neoforge_version
	
	runs {
		client {
			client()
			systemProperty "forge.logging.markers", "REGISTRIES"
			logLevel = org.slf4j.event.Level.DEBUG
		}
	}

	mods {
		"${mod_id}" {
			sourceSet(sourceSets.main)
		}
	}
}

dependencies {
	compileOnly project(":common")

	runtimeOnly "maven.modrinth:forge-config-api-port:21.9.7"
	implementation "maven.modrinth:open-parties-and-claims:neoforge-1.21.9-0.25.6"
	compileOnly("info.journeymap:journeymap-api-neoforge:2.0.0-1.21.9-SNAPSHOT") {changing = true}
	runtimeOnly "maven.modrinth:journeymap:1.21.9-6.0.0-beta.53+neoforge"
}

processResources {
	from project(":common").sourceSets.main.resources

	filesMatching("META-INF/neoforge.mods.toml") {
		expand "mod_id": project.mod_id, "version": project.version,
			"mod_name": project.mod_name, "mod_author": project.mod_author
	}
}

sourceSets.each {
	it.java.srcDirs(project(":common").sourceSets[it.name].java.srcDirs)
}
